version: '3.8'

services:
  nano-board:
    image: garonix/nano-board:latest

    container_name: nano-board
    restart: unless-stopped
    
    ports:
      - "9029:3000"

    environment:
      # 密码验证功能控制 - 通过API动态获取，无需NEXT_PUBLIC_前缀
      - ENABLE_PASSWORD_AUTH=true
      # 自定义访问密码 - 统一使用默认密码，与开发环境保持一致
      - ACCESS_PASSWORD=nano2025

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
