version: '3.8'

services:
  nano-board:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nano-board
    restart: unless-stopped

    ports:
      - "9029:3000"

    environment:
      # 密码验证功能控制
      - ENABLE_PASSWORD_AUTH=${ENABLE_PASSWORD_AUTH:-true}
      # 自定义访问密码（仅在启用密码验证时生效）
      - ACCESS_PASSWORD=${ACCESS_PASSWORD:-nano2024}

    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
